export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const RECEIVE_SESSION_ERRORS = 'RECEIVE_SESSION_ERRORS';

export const BTC_SPARKLINES = 'BTC_SPARKLINES';
export const BCH_SPARKLINES = 'BCH_SPARKLINES';
export const ETH_SPARKLINES = 'ETH_SPARKLINES';
export const ETC_SPARKLINES = 'ETC_SPARKLINES';
export const LTC_SPARKLINES = 'LTC_SPARKLINES';
