export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const RECEIVE_SESSION_ERRORS = 'RECEIVE_SESSION_ERRORS';

export const FETCH_SPARKLINES = 'FETCH_SPARKLINES';
export const FETCH_ASSETS = 'FETCH_ASSETS';
