export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const RECEIVE_SESSION_ERRORS = 'RECEIVE_SESSION_ERRORS';

export const FETCH_WELCOME_24HR_SPARKLINES_DATA = 'FETCH_WELCOME_24HR_SPARKLINES_DATA';
export const FETCH_WELCOME_DECIMAL_DATA = 'FETCH_WELCOME_DECIMAL_DATA';
